### ISSUE TITLE
Coloring in SlideableListItem

### ISSUE THREAD

**Issue by byrialsen** [nmetulev/comet#15]
Hi

Im using SlidableListItem as itemtemplate in a regular UWP Listview control. My problem is related to coloring. I can see that your control has hardcodet colors like background = "White". Is it possible to set this back to how the coloring is defined in the default ListViewItem. Can't seem to find any system resource brush that matches what I want.

Are you able to help me out. I know that the answer to this might be a generel question more that related to your control :-)

**Comment by nmetulev** [comment]
Hey byrialsen, you could specify the background of the SlidableListItem just like any other ContentControl.

`<c:SlidableListItem Background="Yellow"> ... </c:SlidableListItem>`

If however, your question is about how to make it transparent, that is something that is not possible right now, but it is on my list to fix (see #11)

**Comment by byrialsen** [comment]
Hi
.
Thanks for your answer. What I am trying, is to avoid to hardcode any colors. I will prefer to have the operating system/theme telling what actual colors to use. But I can't seem to find any system resource that tells me fx. the background color of an ListViewItem.
Said in another way, I just want the SlideableListItem to use the same colors as a regular ListViewItem.

**Comment by nmetulev** [comment]
I see what you mean. You can see the default style of the [ListViewItem here](https://msdn.microsoft.com/en-us/library/windows/apps/mt299136.aspx). The default Background there is Transparent, but there is also different backgrounds for different states that you can see.
