### ISSUE TITLE
RangeSelector MinRangeChanged and MaxRangeChanged events missing

### ISSUE THREAD

**Issue by LanceMcCarthy** [nmetulev/comet#7]
I see in your RangeSelector demo that you're simply binding a TextBlock to the value, do you have plans to implement a changed event? 

I've had two UWP options for a RangeSelector but one has no events at all and the other only has a single RangeChanged that fires with both StartValue and EndValue values passed in the args.

If you implement an event for the individual values changing, it would bring your RangeSelector to the best in the field :)

Thanks for your consideration!

**Comment by nmetulev** [comment]
Thanks for the feedback Lance. The RangeSelector currently has a ValueChanged event, and I'm adding EventArgs that specify what value was changed, as well as the old and the new value. Would that cover this case, or do you still think two different events is the way to go?

**Comment by nmetulev** [comment]
Added RangeChangedEventArgs that provide the changed property in an enumeration as well as the old and new value. Let me know if that solution does not cover this situation and we can discuss.

**Comment by LanceMcCarthy** [comment]
Thank you!
