### ISSUE TITLE
Can not set ItemContainerTransitions

### ISSUE THREAD

**Issue by h82258652** [nmetulev/comet#9]
``` XAML
<comet:PullToRefreshListView>
    <comet:PullToRefreshListView.ItemContainerTransitions>
        <EntranceThemeTransition IsStaggeringEnabled="True"
                                                    FromVerticalOffset="30"
                                                    FromHorizontalOffset="0"></EntranceThemeTransition>
    </comet:PullToRefreshListView.ItemContainerTransitions>
</comet:PullToRefreshListView>
```

I use this code, but the debugger break down.
Sorry for my english, my mother language is not english.

**Comment by nmetulev** [comment]
Hey h82258652, it looks like this is a complication in xaml, according to this msdn [forum post](https://social.msdn.microsoft.com/Forums/en-US/fcfe3852-1184-42fa-8bf0-5841899211b1/access-violation-exception-when-applying-transitions?forum=winappswithcsharp). Try wrapping EntranceThemeTransition in TransitionCollection.

**Comment by h82258652** [comment]
Oh, thanks. It works now.^-^
